---

- name: Create Servicemix Install Directory
  file:
    path: /opt/servicemix
    state: directory
    owner: ec2-user
    group: ec2-user
    mode: 0777
  become: true
  become_user: root

- name: Create Servicemix Temp Directory
  file:
    path: /tmp/servicemixtemp
    state: directory
    mode: 0777

- name: Download Apache Servicemix
  get_url:
    url: "{{ service_mix_dstblnk }}"
    dest: /tmp/servicemixtemp
    mode: 0777

- name: Unpack Apache Servicemix
  unarchive:
    src: /tmp/servicemixtemp/apache-servicemix-7.0.1.zip
    dest: /opt/servicemix
    owner: ec2-user
    group: ec2-user
    mode: 0777
    remote_src: yes
  become: true
  become_user: root

- name: Start the Karaf Container
  command: "sudo /opt/servicemix/apache-servicemix-7.0.1/bin/start"
  register: start_output

- name: Pausing for the Karaf container to start and available on 8101
  wait_for:
    port: 8101
    delay: 10

- name: Delete the Servicemix Temp Directory
  file:
   path: /tmp/servicemixtemp
   state: absent